# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "quenty/rojo@7.4.3-quenty-npm-canary.2"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "Kampfkarren/selene@0.27.1"
moonwave-extractor = "UpliftGames/moonwave@1.1.2"
mantle = "blake-mealey/mantle@0.10.7"
remodel = "rojo-rbx/remodel@0.9.1"